### ISSUE TITLE
Not working with Laravel 10.14

### ISSUE THREAD

**Issue by cmitexperts** [sander3/laravel-sendcloud#9]
Hey, Thank you for this awesome package.

It's giving error during installation with laravel version 10.14 & PHP version is: 8.2

Please see error below:

Problem 1
    - soved/laravel-sendcloud[v0.1.0, ..., v0.2.1] require php ^7.4 -> your php version (8.2.0) does not satisfy that requirement.
    - soved/laravel-sendcloud[v0.3.0, ..., v0.3.2, v1.0.0] require illuminate/http ^8.0 -> found illuminate/http[v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - soved/laravel-sendcloud[v1.1.0, ..., v1.2.3] require illuminate/http ^8.0|^9.0 -> found illuminate/http[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.10] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires soved/laravel-sendcloud * -> satisfiable by soved/laravel-sendcloud[v0.1.0, ..., v0.3.2, v1.0.0, ..., v1.2.3].
    
Can you please let me know what I'm missing?

**Comment by sander3** [comment]
Hi @cmitexperts,

Sorry, it seems like I forgot to tag a new release when adding Laravel 10 support.

Could you try again?

**Comment by cmitexperts** [comment]
@sander3,

Yes, it working now again many thanks :)

**Comment by cmitexperts** [comment]
@sander3 

Yes, it's working now again many thanks :)
